-- fittrack-api initial schema.
-- Written in portable SQL so the identical migration runs on PostgreSQL
-- (production) and H2 in PostgreSQL-compatibility mode (tests).

CREATE TABLE exercise (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(120) NOT NULL,
    muscle_group VARCHAR(20)  NOT NULL,
    category     VARCHAR(20)  NOT NULL,
    description  VARCHAR(500),
    CONSTRAINT uq_exercise_name UNIQUE (name)
);

CREATE TABLE workout (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    performed_on DATE         NOT NULL,
    title        VARCHAR(255) NOT NULL,
    notes        VARCHAR(1000),
    created_at   TIMESTAMP    NOT NULL
);

CREATE INDEX idx_workout_performed_on ON workout (performed_on);

CREATE TABLE workout_set (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_id  BIGINT       NOT NULL,
    exercise_id BIGINT       NOT NULL,
    set_number  INT          NOT NULL,
    reps        INT          NOT NULL,
    weight_kg   NUMERIC(6, 2) NOT NULL,
    rpe         INT,
    CONSTRAINT fk_set_workout  FOREIGN KEY (workout_id)  REFERENCES workout (id)  ON DELETE CASCADE,
    CONSTRAINT fk_set_exercise FOREIGN KEY (exercise_id) REFERENCES exercise (id),
    CONSTRAINT ck_set_reps     CHECK (reps > 0),
    CONSTRAINT ck_set_rpe      CHECK (rpe IS NULL OR (rpe BETWEEN 1 AND 10))
);

CREATE INDEX idx_set_workout  ON workout_set (workout_id);
CREATE INDEX idx_set_exercise ON workout_set (exercise_id);

CREATE TABLE body_metric (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    measured_on  DATE          NOT NULL,
    weight_kg    NUMERIC(5, 2) NOT NULL,
    body_fat_pct NUMERIC(4, 1),
    resting_hr   INT,
    CONSTRAINT uq_body_metric_date UNIQUE (measured_on)
);
